const numbersData = [
  {
    english: "One",
    hindi: "एक",
    transliteration: "Ek",
    example: "I have one book.",
    sound: "/Audio/1.mp3",
  },
  {
    english: "Two",
    hindi: "दो",
    transliteration: "Do",
    example: "I have two pens.",
    sound: "/Audio/2.mp3",
  },
  {
    english: "Three",
    hindi: "तीन",
    transliteration: "Teen",
    example: "There are three apples.",
    sound: "/Audio/3.mp3",
  },
  {
    english: "Four",
    hindi: "चार",
    transliteration: "Chaar",
    example: "She has four bags.",
    sound: "/Audio/4.mp3",
  },
  {
    english: "Five",
    hindi: "पाँच",
    transliteration: "Paanch",
    example: "Give me five minutes.",
    sound: "/Audio/5.mp3",
  },
  {
    english: "Six",
    hindi: "छह",
    transliteration: "Chhah",
    example: "He bought six books.",
    sound: "/Audio/6.mp3",
  },
  {
    english: "Seven",
    hindi: "सात",
    transliteration: "Saat",
    example: "There are seven days.",
    sound: "/Audio/7.mp3",
  },
  {
    english: "Eight",
    hindi: "आठ",
    transliteration: "Aath",
    example: "She woke up at eight.",
    sound: "/Audio/8.mp3",
  },
  {
    english: "Nine",
    hindi: "नौ",
    transliteration: "Nau",
    example: "It is nine o'clock.",
    sound: "/Audio/9.mp3",
  },
  {
    english: "Ten",
    hindi: "दस",
    transliteration: "Das",
    example: "I counted to ten.",
    sound: "/Audio/10.mp3",
  },

  {
    english: "Twenty",
    hindi: "बीस",
    transliteration: "Bees",
    example: "I am twenty years old.",
    sound: "/Audio/20.mp3",
  },
  {
    english: "Thirty",
    hindi: "तीस",
    transliteration: "Tees",
    example: "He has thirty students.",
    sound: "/Audio/30.mp3",
  },
  {
    english: "Forty",
    hindi: "चालीस",
    transliteration: "Chalees",
    example: "The price is forty rupees.",
    sound: "/Audio/40.mp3",
  },
  {
    english: "Fifty",
    hindi: "पचास",
    transliteration: "Pachaas",
    example: "She bought fifty flowers.",
    sound: "/Audio/50.mp3",
  },
  {
    english: "Sixty",
    hindi: "साठ",
    transliteration: "Saath",
    example: "He ran sixty meters.",
    sound: "/Audio/60.mp3",
  },
  {
    english: "Seventy",
    hindi: "सत्तर",
    transliteration: "Sattar",
    example: "There are seventy people.",
    sound: "/Audio/70.mp3",
  },
  {
    english: "Eighty",
    hindi: "अस्सी",
    transliteration: "Assi",
    example: "She scored eighty marks.",
    sound: "/Audio/80.mp3",
  },
  {
    english: "Ninety",
    hindi: "नब्बे",
    transliteration: "Nabbe",
    example: "He saved ninety dollars.",
    sound: "/Audio/90.mp3",
  },
  {
    english: "One Hundred",
    hindi: "एक सौ",
    transliteration: "Ek Sau",
    example: "There are one hundred students.",
    sound: "/Audio/100.mp3",
  },
];

export default numbersData;