import React from 'react'

const vocabularyData = [
     {
    english: "Hello",
    hindi: "नमस्ते",
    transliteration: "Namaste",
    example: "Hello! How are you?",
    sound: "/Audio/hello.mp3",
  },
  {
    english: "Greetings",
    hindi: "नमस्कार",
    transliteration: "Namaskar",
    example: "Greetings! Welcome.",
    sound: "/Audio/greetings.mp3",
  },
  {
    english: "Good Morning",
    hindi: "सुप्रभात",
    transliteration: "Suprabhat",
    example: "Good morning!",
    sound: "/Audio/good-morning.mp3",
  },
  {
    english: "Good Evening",
    hindi: "शुभ संध्या",
    transliteration: "Shubh Sandhya",
    example: "Good evening!",
    sound: "/Audio/good-evening.mp3",
  },
  {
    english: "Good Night",
    hindi: "शुभ रात्रि",
    transliteration: "Shubh Ratri",
    example: "Good night!",
    sound: "/Audio/good-night.mp3",
  },
  {
    english: "Goodbye",
    hindi: "अलविदा",
    transliteration: "Alvida",
    example: "Goodbye! See you again.",
    sound: "/Audio/goodbye.mp3",
  },
  {
    english: "See you again",
    hindi: "फिर मिलेंगे",
    transliteration: "Phir milenge",
    example: "See you again tomorrow.",
    sound: "/Audio/see-you.mp3",
  },
  {
    english: "How are you?",
    hindi: "आप कैसे हैं?",
    transliteration: "Aap kaise hain?",
    example: "How are you today?",
    sound: "/Audio/how-are-you.mp3",
  },
  {
    english: "I am fine",
    hindi: "मैं ठीक हूँ",
    transliteration: "Main theek hoon",
    example: "I am fine.",
    sound: "/Audio/i-am-fine.mp3",
  },
  {
    english: "Thank you",
    hindi: "धन्यवाद",
    transliteration: "Dhanyavaad",
    example: "Thank you for your help.",
    sound: "/Audio/thank-you.mp3",
  },
  {
    english: "Thanks",
    hindi: "शुक्रिया",
    transliteration: "Shukriya",
    example: "Thanks!",
    sound: "/Audio/thanks.mp3",
  },
  {
    english: "Please",
    hindi: "कृपया",
    transliteration: "Kripya",
    example: "Please sit here.",
    sound: "/Audio/please.mp3",
  },
  {
    english: "Excuse me",
    hindi: "माफ कीजिए",
    transliteration: "Maaf kijiye",
    example: "Excuse me, can you help?",
    sound: "/Audio/excuse-me.mp3",
  },
  {
    english: "Sorry",
    hindi: "क्षमा कीजिए",
    transliteration: "Kshama kijiye",
    example: "Sorry for the mistake.",
    sound: "/Audio/sorry.mp3",
  },
  {
    english: "No problem",
    hindi: "कोई बात नहीं",
    transliteration: "Koi baat nahi",
    example: "No problem.",
    sound: "/Audio/no-problem.mp3",
  },
  {
    english: "What is your name?",
    hindi: "आपका नाम क्या है?",
    transliteration: "Aapka naam kya hai?",
    example: "What is your name?",
    sound: "/Audio/what-is-your-name.mp3",
  },
  {
    english: "My name is...",
    hindi: "मेरा नाम ... है",
    transliteration: "Mera naam ... hai",
    example: "My name is Rahul.",
    sound: "/Audio/my-name-is.mp3",
  },
  {
    english: "Nice to meet you",
    hindi: "आपसे मिलकर खुशी हुई",
    transliteration: "Aapse milkar khushi hui",
    example: "Nice to meet you.",
    sound: "/Audio/nice-to-meet-you.mp3",
  },
  {
    english: "Welcome",
    hindi: "स्वागत है",
    transliteration: "Swagat hai",
    example: "Welcome to our home.",
    sound: "/Audio/welcome.mp3",
  },
  {
    english: "Yes",
    hindi: "हाँ",
    transliteration: "Haan",
    example: "Yes, I agree.",
    sound: "/Audio/yes.mp3",
  },
  {
    english: "No",
    hindi: "नहीं",
    transliteration: "Nahi",
    example: "No, thank you.",
    sound: "/Audio/no.mp3",
  },
  {
    english: "Okay",
    hindi: "ठीक है",
    transliteration: "Theek hai",
    example: "Okay, let's go.",
    sound: "/Audio/okay.mp3",
  },
  {
    english: "Friend",
    hindi: "दोस्त",
    transliteration: "Dost",
    example: "He is my friend.",
    sound: "/Audio/friend.mp3",
  },
  {
    english: "Sir",
    hindi: "श्रीमान",
    transliteration: "Shrimaan",
    example: "Good morning, sir.",
    sound: "/Audio/sir.mp3",
  },
  {
    english: "Madam",
    hindi: "श्रीमती",
    transliteration: "Shrimati",
    example: "Hello, madam.",
    sound: "/Audio/madam.mp3",
  },
];

export default vocabularyData